# Generated by Django 4.0.1 on 2022-01-15 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccessMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=50, null=True)),
                ('code', models.CharField(blank=True, max_length=7, null=True)),
                ('typ', models.CharField(blank=True, max_length=6, null=True)),
                ('parentCode', models.CharField(blank=True, max_length=7, null=True)),
                ('desc', models.CharField(blank=True, max_length=200, null=True)),
                ('text', models.CharField(blank=True, max_length=12, null=True)),
                ('icon', models.CharField(blank=True, max_length=40, null=True)),
                ('path', models.CharField(blank=True, max_length=40, null=True)),
                ('badge', models.CharField(blank=True, max_length=7, null=True)),
                ('badgeContent', models.CharField(blank=True, max_length=20, null=True)),
                ('access', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'useraccessmenu_map',
                'ordering': ('username', 'code'),
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MainMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='DEF', max_length=7)),
                ('typ', models.CharField(choices=[('1', 'Main'), ('2', 'Parent'), ('3', 'Child')], default='Child', max_length=6)),
                ('parentCode', models.CharField(blank=True, max_length=7, null=True)),
                ('desc', models.CharField(blank=True, max_length=200, null=True)),
                ('text', models.CharField(default='TextMenu', max_length=12)),
                ('icon', models.CharField(default='bx bx-data', max_length=40)),
                ('path', models.CharField(default='/login', max_length=40)),
                ('badge', models.CharField(blank=True, max_length=7, null=True)),
                ('badgeContent', models.CharField(blank=True, max_length=20, null=True)),
                ('createdAt', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ('typ', 'code'),
            },
        ),
    ]
