# Generated by Django 4.0.1 on 2022-01-15 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServerListModel',
            fields=[
                ('Server_Status', models.CharField(blank=True, max_length=50, null=True)),
                ('Name', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('Hostname', models.CharField(blank=True, max_length=60, null=True)),
                ('IP', models.CharField(blank=True, max_length=20, null=True)),
                ('Windows_Server', models.CharField(blank=True, max_length=50, null=True)),
                ('CPU', models.CharField(blank=True, max_length=20, null=True)),
                ('Memory', models.CharField(blank=True, max_length=20, null=True)),
                ('SQL_Version', models.CharField(blank=True, max_length=50, null=True)),
                ('Disc_Size', models.CharField(blank=True, max_length=20, null=True)),
                ('Location', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StoreMasterModel',
            fields=[
                ('ASOFDATE', models.CharField(blank=True, max_length=50, null=True)),
                ('COMPCODE', models.CharField(blank=True, max_length=5, null=True)),
                ('SITECODE', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('STOREDESC', models.CharField(blank=True, max_length=50, null=True)),
                ('MALLNAME', models.CharField(blank=True, max_length=50, null=True)),
                ('TELP', models.CharField(blank=True, max_length=30, null=True)),
                ('EMAIL', models.CharField(blank=True, max_length=30, null=True)),
                ('CONCEPT', models.CharField(blank=True, max_length=30, null=True)),
                ('PROVINCE', models.CharField(blank=True, max_length=30, null=True)),
                ('REGION', models.CharField(blank=True, max_length=30, null=True)),
                ('GM_OM', models.CharField(blank=True, max_length=30, null=True)),
                ('GM_MAIL', models.CharField(blank=True, max_length=30, null=True)),
                ('OM_NAME', models.CharField(blank=True, max_length=30, null=True)),
                ('OM_MAIL', models.CharField(blank=True, max_length=30, null=True)),
                ('OM_PHONE', models.CharField(blank=True, max_length=30, null=True)),
                ('OIC_NAME', models.CharField(blank=True, max_length=30, null=True)),
                ('OIC_MAIL', models.CharField(blank=True, max_length=30, null=True)),
                ('OIC_PHONE', models.CharField(blank=True, max_length=30, null=True)),
                ('SBU', models.CharField(blank=True, max_length=5, null=True)),
                ('STORETYPE', models.CharField(blank=True, max_length=10, null=True)),
                ('SITEPROFILE', models.CharField(blank=True, max_length=20, null=True)),
                ('CONNECTION_TYPE', models.CharField(blank=True, max_length=20, null=True)),
                ('STORESTATUS_SQL', models.CharField(blank=True, max_length=20, null=True)),
                ('STOREOPEN_DATE', models.CharField(blank=True, max_length=20, null=True)),
                ('STORECLOSE_DATE', models.CharField(blank=True, max_length=20, null=True)),
                ('FAILOVER_STATUS', models.CharField(blank=True, max_length=20, null=True)),
                ('JASPER_NUMBER_DEVICE', models.CharField(blank=True, max_length=20, null=True)),
                ('JASPESR_DEVICE', models.CharField(blank=True, max_length=20, null=True)),
                ('JASPER_IPADDRESS', models.CharField(blank=True, max_length=20, null=True)),
                ('JASPER_MSISDN', models.CharField(blank=True, max_length=20, null=True)),
                ('JASPER_IMSI', models.CharField(blank=True, max_length=20, null=True)),
                ('ROOT_STATUS', models.CharField(blank=True, max_length=20, null=True)),
                ('IP_EXTERNAL', models.CharField(blank=True, max_length=20, null=True)),
                ('IP_MIKROTIK', models.CharField(blank=True, max_length=20, null=True)),
                ('IP_GATEWAY', models.CharField(blank=True, max_length=20, null=True)),
                ('IP_FORTIGATE', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
